### ISSUE TITLE
I am getting this error 

### ISSUE THREAD

**Issue by eswar-gaiansolutions** [shoebham/text_to_isl#11]
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    en_nlp = stanza.Pipeline('en',processors={'tokenize':'spacy'})
  File "/home/gaian/.local/lib/python3.8/site-packages/stanza/pipeline/core.py", line 139, in __init__
    self.processors[processor_name] = NAME_TO_PROCESSOR_CLASS[processor_name](config=curr_processor_config,
  File "/home/gaian/.local/lib/python3.8/site-packages/stanza/pipeline/processor.py", line 159, in __init__
    self._set_up_model(config, use_gpu)
  File "/home/gaian/.local/lib/python3.8/site-packages/stanza/pipeline/pos_processor.py", line 25, in _set_up_model
    self._trainer = Trainer(pretrain=self.pretrain, model_file=config['model_path'], use_cuda=use_gpu)
  File "/home/gaian/.local/lib/python3.8/site-packages/stanza/models/pos/trainer.py", line 35, in __init__
    self.load(model_file, pretrain)
  File "/home/gaian/.local/lib/python3.8/site-packages/stanza/models/pos/trainer.py", line 120, in load
    self.model.load_state_dict(checkpoint['model'], strict=False)
  File "/home/gaian/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1406, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Tagger:
        size mismatch for drop_replacement: copying a param with shape torch.Size([2248]) from checkpoint, the shape in current model is torch.Size([325]).
        size mismatch for taggerlstm.lstm.0.lstm.weight_ih_l0: copying a param with shape torch.Size([800, 2248]) from checkpoint, the shape in current model is torch.Size([800, 325]).
        size mismatch for taggerlstm.lstm.0.lstm.weight_ih_l0_reverse: copying a param with shape torch.Size([800, 2248]) from checkpoint, the shape in current model is torch.Size([800, 325]).
        size mismatch for taggerlstm.highway.0.weight: copying a param with shape torch.Size([400, 2248]) from checkpoint, the shape in current model is torch.Size([400, 325]).
        size mismatch for taggerlstm.gate.0.weight: copying a param with shape torch.Size([400, 2248]) from checkpoint, the shape in current model is torch.Size([400, 325]).

**Comment by shoebham** [comment]
Did you install spacy?
try installing all the required modules with
```
pip install -r requirements.txt
``` 
additionally install spacy as that is not in requirements.txt 
by :
```
pip install spacy
```

**Comment by eswar-gaiansolutions** [comment]
After Installing  spacy also it did not worked

**Comment by shoebham** [comment]
is it giving same error after installing spacy. 
please elaborate more on your comments always provide as much information as you can.

**Comment by vinay0981123** [comment]
same here getting same error.

**Comment by vinay0981123** [comment]
Ok let me tell you more my python version is 3.9.8 and pip is 21.2.4 and I followed the instruction and successfully installed everything including spacy following mentioned version now getting the error and i didnt activated venv installed everything globally now please let me know if this is happening due to some conflict or some version issue?
![image](https://github.com/shoebham/text_to_isl/assets/85073024/ce555d3b-4685-46d4-a517-4ea9fff76ba5)
![image](https://github.com/shoebham/text_to_isl/assets/85073024/1871c60d-5d77-4771-8c46-079564d1f330)

**Comment by shoebham** [comment]
spacy might have changed their model.
can you please run 
``` 
pip show spacy
pip show stanza
```

It is most likely a version issue.
The project runs fine on my system. my versions are 
python: 3.9.0
spacy: 3.5.2
stanza: 1.4.0

and urllib one is just a warning that you can ignore.
I will fix the version compatibility issue in the future. for now please install these versions.

**Comment by vinay0981123** [comment]
getting output:
![image](https://github.com/shoebham/text_to_isl/assets/85073024/c489e76f-8197-47a1-a9d5-84664ae6090d)

**Comment by vinay0981123** [comment]
See initially I was using latest version of python and pip and while installing i was having issue with installation something like build issue so i seen this was happening because of latest pip so i manually installed every modules and started your program then i was passing text but it was not able to recieve the text and it was sending the error stanford-parser-full-2018-10-17.zip not found or not accessible i checked this link there were a message service is close till 3 july now you can check the link again for the file its showing 404 not found then i changed the version of python with 3.9.8 and again installed every dependecies without having any issue with the same version what you mentioned but now giving this error.

**Comment by shoebham** [comment]
I just saw that the page is returning 404.
I have uploaded the zip file on my drive, just paste it in the same folder as main.py
https://drive.google.com/file/d/1lEafb759ZbA33VNvwZOr0fznhtC4Kf4P/view

rest i think you got the project working if you were able to enter the text, with this zip you'll be fine

**Comment by vinay0981123** [comment]
getting this error now when i submit text to convert.
![image](https://github.com/shoebham/text_to_isl/assets/85073024/4d10bbdd-f9b7-4ea3-9d33-053048c642cf)
![image](https://github.com/shoebham/text_to_isl/assets/85073024/644d460c-1fd6-457b-bf3a-4ba85d7aaed8)
![image](https://github.com/shoebham/text_to_isl/assets/85073024/8b27d165-4bd3-4c32-98bc-fbd2075757b1)
![image](https://github.com/shoebham/text_to_isl/assets/85073024/5e5078e7-8d54-42a8-8da6-148e230966c3)
![image](https://github.com/shoebham/text_to_isl/assets/85073024/92dc7ad6-dec3-4788-bc1e-7306715be966)

**Comment by shoebham** [comment]
try setting this inside path
%JAVA_HOME%\bin
![image](https://github.com/shoebham/text_to_isl/assets/25881429/df7a7019-35f6-4447-b8d2-3fa873b398f9)

and did you restart vscode after setting java home cause we need to restart the terminal after setting variables

**Comment by shoebham** [comment]
and try not putting multiple paths like you have put oracle one twice, remove them both and just set %JAVA_HOME%\bin

**Comment by vinay0981123** [comment]
Thank you so much bro its working fine now but see this if we can ignore that part in red one
![image](https://github.com/shoebham/text_to_isl/assets/85073024/ac146808-15f3-46dc-8bf4-bddcf359c224)

**Comment by vinay0981123** [comment]
Now facing this issue. this worked fine 2 to 3 times but now having issue
![image](https://github.com/shoebham/text_to_isl/assets/85073024/c5e7885a-f372-41fb-9001-83764c4007d5)

**Comment by shoebham** [comment]
> Now facing this issue. this worked fine 2 to 3 times but now having issue
> ![image](https://github.com/shoebham/text_to_isl/assets/85073024/c5e7885a-f372-41fb-9001-83764c4007d5)
> 

just retry it will work it sometimes happen

**Comment by atharvauk15** [comment]
> I just saw that the page is returning 404. I have uploaded the zip file on my drive, just paste it in the same folder as main.py https://drive.google.com/file/d/1lEafb759ZbA33VNvwZOr0fznhtC4Kf4P/view
> 
> rest i think you got the project working if you were able to enter the text, with this zip you'll be fine

I dont have to extract the file right?
Just directly paste it inside the folder containing main.py?

**Comment by shoebham** [comment]
You can extract it or the let the code extract up to you
