### ISSUE TITLE
I am facing this issue. Kindly resolve it urgently

### ISSUE THREAD

**Issue by ashmeet0906** [shoebham/text_to_isl#12]
![Screenshot 2023-11-19 003158](https://github.com/shoebham/text_to_isl/assets/103422145/af6cc493-198e-4aa2-b94a-cbeb3be2a369)
pls check this and tell the solution. I have downloaded and unzipped stanford parser as well

**Comment by shoebham** [comment]
seems like a problem on your end works fine for me.
Can you elaborate more on this. 
Give the full stack trace
