### ISSUE TITLE
the provided link is not working

### ISSUE THREAD

**Issue by amruta16-mk** [shoebham/text_to_isl#13]
after pasting this link  http://127.0.0.1:5000/ I'm getting This site can’t be reached. Please Help me its urgent.

**Comment by amruta16-mk** [comment]
Please help me, I am facing this issue. after running command: python main.py

![WhatsApp Image 2023-12-28 at 11 19 03 PM](https://github.com/shoebham/text_to_isl/assets/97730979/3c21bce8-d565-4f84-9d3f-602b04b7db58)
![WhatsApp Image 2023-12-28 at 11 19 03 PM (1)](https://github.com/shoebham/text_to_isl/assets/97730979/c042f779-2212-4993-8799-080497cacd1e)

**Comment by shoebham** [comment]
I haven't encountered this issue before. 
can you list down the steps you did to get this? also mention what python version are you running
