### ISSUE TITLE
UTF-8 codec can't decode byte 0×e9 in position 122

### ISSUE THREAD

**Issue by ikrammohamdi** [shoebham/text_to_isl#14]
the avatar does not move when the command is entered 
I use python 3.9.0 SPACY 3.5.2 stanza 1.4.0
![Capture 2](https://github.com/shoebham/text_to_isl/assets/161083938/0a7ac5dc-4ea0-447e-9d71-5457df54ee51)

**Comment by shoebham** [comment]
You'll have to provide me more details for me to help you. the screenshot you attached just shows warnings that is not the actual error. 
Click on terminal to see the ouput.

**Comment by ikrammohamdi** [comment]
When I enter the alphabet like a b , avatar moves, and when I write a sentence like how are you?, it does not move
![Uploading 17097455929397689807945759167253.jpg…]()

**Comment by shoebham** [comment]
@ikrammohamdi your image is not uploaded properly. wait for it to upload while commenting. also if possible provide stacktrace from terminal

**Comment by ikrammohamdi** [comment]
> @ikrammohamdi your image is not uploaded properly. wait for it to upload while commenting. also if possible provide stacktrace from terminal

**Comment by ikrammohamdi** [comment]
![Capture3](https://github.com/shoebham/text_to_isl/assets/161083938/eabb6626-6375-4caf-a289-21431f3ae3d9)

**Comment by shoebham** [comment]
CAN YOU PROVIDE ME SCREENSHOT OF TERMINAL ALSO???

**Comment by ikrammohamdi** [comment]
![Capture 4](https://github.com/shoebham/text_to_isl/assets/161083938/4b80cdfd-6f6e-4bdc-8ebb-a416357bdca2)

**Comment by shoebham** [comment]
The error is in front of your eyes, you can try fixing it yourself. have you tried anything?

**Comment by shoebham** [comment]
@ikrammohamdi pls mention the steps to reproduce this issue. It works fine on my end

**Comment by ikrammohamdi** [comment]
@shoebham When I type how are you?  in the input and click submit, the avatar does not move

**Comment by shoebham** [comment]
Google the errors and try fixing it.

**Comment by ikrammohamdi** [comment]
@shoebham i tried to solve the problem but the same thing 
![Capture6](https://github.com/shoebham/text_to_isl/assets/161083938/1f5b74f9-5921-4a34-8648-880b23a68726)

**Comment by shoebham** [comment]
I think your input is in another language,  which might be causing the problems. 0xe9 corresponds to é in Latin.
<img width="786" alt="image" src="https://github.com/shoebham/text_to_isl/assets/25881429/f5615d2f-7e16-4503-aba8-7bef6ea85a2c">

This seems to be the root of the issue. 
If you're using windows try changing your input to english utf-8. 

or try copying hello from this comment in the input box.

if you find any solution to fix this in the code, please raise a PR.

**Comment by ikrammohamdi** [comment]
Ok ,thanks

**Comment by shoebham** [comment]
did that work?

**Comment by ikrammohamdi** [comment]
when running the code , i saw this 
![7](https://github.com/shoebham/text_to_isl/assets/161083938/98c1a041-62f3-450e-9aac-86e17da27c8f)

**Comment by shoebham** [comment]
https://github.com/explosion/spaCy/issues/12659

**Comment by ikrammohamdi** [comment]
so when I copied hello from your comment  it didn't work
![8](https://github.com/shoebham/text_to_isl/assets/161083938/396e107f-7bc3-4b82-b8be-e3153d01050a)

**Comment by shoebham** [comment]
change input to only utf8
