### ISSUE TITLE
Used version 

### ISSUE THREAD

**Issue by ikrammohamdi** [shoebham/text_to_isl#15]
I want to know the version of nltk used in the code

**Comment by shoebham** [comment]
<img width="493" alt="image" src="https://github.com/shoebham/text_to_isl/assets/25881429/30f8972b-5668-4a51-888d-ea4fa82f432a">

**Comment by ikrammohamdi** [comment]
I have this problem and I haven't been able to solve it
![10](https://github.com/shoebham/text_to_isl/assets/161083938/6a8a6931-b387-42be-8f30-c5fef3d27ca0)

**Comment by shoebham** [comment]
Honestly, i don't about this error.
I have updated the requirements with all dependencies that I have, kindly uninstall your dependencies and pip install requirements.txt of [this](https://github.com/shoebham/text_to_isl/blob/main/requirements.txt) file

**Comment by ikrammohamdi** [comment]
so , should i delete the line 1,16,27 of requirements.txt ?
![11](https://github.com/shoebham/text_to_isl/assets/161083938/6613a6d0-f216-47dd-b3cc-e2a090eeea21)
