### ISSUE TITLE
Gets internal 500 error after loading avatar

### ISSUE THREAD

**Issue by AjnasNB** [shoebham/text_to_isl#16]
![image](https://github.com/shoebham/text_to_isl/assets/114915484/f85bf435-b168-40fd-bfcd-d9d7844e8f9c)

**Comment by shoebham** [comment]
brother, 500 error is usually printed on the server. Look at your console.

**Comment by AjnasNB** [comment]
The problem is it's loading but not working when I type something in.
It's not taking the text input and generating the output and the code seems
to be correct

**Comment by shoebham** [comment]
you have to see the terminal console from where you run the code to see the error
