### ISSUE TITLE
post error

### ISSUE THREAD

**Issue by Naren020402** [shoebham/text_to_isl#18]
127.0.0.1 - - [29/Apr/2024 15:15:52] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2024 15:15:52] "GET /css/cwasa.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Apr/2024 15:15:52] "GET /style.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Apr/2024 15:15:52] "GET /js/script.js HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2024 15:15:52] "GET /js/allcsa.js HTTP/1.1" 304 -
here
127.0.0.1 - - [29/Apr/2024 15:15:52] "GET /static/js/sigmlFiles.json HTTP/1.1" 304 -
127.0.0.1 - - [29/Apr/2024 15:15:52] "GET /jas/loc2021/cwa/cwacfg.json HTTP/1.1" 304 -
127.0.0.1 - - [29/Apr/2024 15:15:52] "HEAD /jas/loc2021/avatars/COMMON.jar HTTP/1.1" 304 -
127.0.0.1 - - [29/Apr/2024 15:15:52] "GET /jas/loc2021/cwa/h2s.xsl HTTP/1.1" 304 -
127.0.0.1 - - [29/Apr/2024 15:15:53] "GET /jas/loc2021/avatars/COMMON.jar HTTP/1.1" 304 -
127.0.0.1 - - [29/Apr/2024 15:15:53] "HEAD /jas/loc2021/avatars/marc.jar HTTP/1.1" 304 -
127.0.0.1 - - [29/Apr/2024 15:15:53] "GET /jas/loc2021/avatars/marc.jar HTTP/1.1" 304 -
127.0.0.1 - - [29/Apr/2024 15:15:53] "GET /jas/loc2021/cwa/shaders/qskin.vert HTTP/1.1" 304 -
127.0.0.1 - - [29/Apr/2024 15:15:53] "GET /jas/loc2021/cwa/shaders/qskin.frag HTTP/1.1" 304 -
text is how are you
C:\Users\Naren\OneDrive\Desktop\text_to_isl-main\main.py:254: DeprecationWarning: The StanfordParser will be deprecated
Please use nltk.parse.corenlp.CoreNLPParser instead.
  parser = StanfordParser()
Error: Could not find or load main class edu.stanford.nlp.parser.lexparser.LexicalizedParser
Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.parser.lexparser.LexicalizedParser

[2024-04-29 15:15:58,874] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\Naren\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Naren\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Naren\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Naren\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Naren\OneDrive\Desktop\text_to_isl-main\main.py", line 375, in flask_test
    take_input(text)
  File "C:\Users\Naren\OneDrive\Desktop\text_to_isl-main\main.py", line 321, in take_input
    convert(some_text);
    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Naren\OneDrive\Desktop\text_to_isl-main\main.py", line 330, in convert
    word_list[i]=reorder_eng_to_isl(words)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Naren\OneDrive\Desktop\text_to_isl-main\main.py", line 256, in reorder_eng_to_isl
    possible_parse_tree_list = [tree for tree in parser.parse(input_string)]
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Naren\AppData\Local\Programs\Python\Python311\Lib\site-packages\nltk\parse\api.py", line 47, in parse
    return next(self.parse_sents([sent], *args, **kwargs))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Naren\AppData\Local\Programs\Python\Python311\Lib\site-packages\nltk\parse\stanford.py", line 136, in parse_sents
    self._execute(
  File "C:\Users\Naren\AppData\Local\Programs\Python\Python311\Lib\site-packages\nltk\parse\stanford.py", line 258, in _execute
    stdout, stderr = java(
                     ^^^^^
  File "C:\Users\Naren\AppData\Local\Programs\Python\Python311\Lib\site-packages\nltk\internals.py", line 146, in java
    raise OSError("Java command failed : " + str(cmd))
OSError: Java command failed : ['C:\\Program Files\\Java\\jdk-21\\bin\\java.exe', '-mx4g', '-cp', 'C:\\Users\\Naren\\OneDrive\\Desktop\\text_to_isl-main\\stanford-parser-full-2018-10-17\\stanford-parser-3.9.2-models.jar;C:\\Users\\Naren\\OneDrive\\Desktop\\text_to_isl-main\\stanford-parser-full-2018-10-17\\ejml-0.23.jar;C:\\Users\\Naren\\OneDrive\\Desktop\\text_to_isl-main\\stanford-parser-full-2018-10-17\\slf4j-api-1.7.12-sources.jar;C:\\Users\\Naren\\OneDrive\\Desktop\\text_to_isl-main\\stanford-parser-full-2018-10-17\\slf4j-api.jar;C:\\Users\\Naren\\OneDrive\\Desktop\\text_to_isl-main\\stanford-parser-full-2018-10-17\\stanford-parser-3.9.2-javadoc.jar;C:\\Users\\Naren\\OneDrive\\Desktop\\text_to_isl-main\\stanford-parser-full-2018-10-17\\stanford-parser-3.9.2-models.jar;C:\\Users\\Naren\\OneDrive\\Desktop\\text_to_isl-main\\stanford-parser-full-2018-10-17\\stanford-parser-3.9.2-sources.jar;C:\\Users\\Naren\\OneDrive\\Desktop\\text_to_isl-main\\stanford-parser-full-2018-10-17\\stanford-parser.jar', 'edu.stanford.nlp.parser.lexparser.LexicalizedParser', '-model', 'edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz', '-sentences', 'newline', '-outputFormat', 'penn', '-tokenized', '-escaper', 'edu.stanford.nlp.process.PTBEscapingProcessor', '-encoding', 'utf8', 'C:\\Users\\Naren\\AppData\\Local\\Temp\\tmpvnuozjfm']
127.0.0.1 - - [29/Apr/2024 15:15:58] "POST / HTTP/1.1" 500 -

this is the error i got
tps://github.com/shoebham/text_to_isl/assets/168421688/a8c5f4aa-19d2-46c1-ad7d-2aab7a130b3b)

**Comment by Naren020402** [comment]
![error](https://github.com/shoebham/text_to_isl/assets/168421688/00a66257-8896-4de3-a6d2-425178b7dfee)

**Comment by shoebham** [comment]
do you have java in your system and in your environment variables???

**Comment by Naren020402** [comment]
> do you have java in your system and in your environment variables???

Yes I have  and have done accordingly how you mentioned

**Comment by Naren020402** [comment]
![Screenshot 2024-04-29 193406](https://github.com/shoebham/text_to_isl/assets/168421688/3e9bbaea-e90e-4d22-adf7-c17569084d68)

**Comment by shoebham** [comment]
maybe try with java 8

**Comment by Naren020402** [comment]
getting same error i tired with java 8
![Screenshot 2024-04-29 194939](https://github.com/shoebham/text_to_isl/assets/168421688/9b660d4e-da65-42df-a9d3-395bfe56c26e)

**Comment by shoebham** [comment]
have you tried the docker solution

**Comment by Naren020402** [comment]
i am not familiar with docker can you provide the link for downloading docker and how to do run it

**Comment by shoebham** [comment]
you dont have the proper resources thats why you're getting the class not found error.
try downloading the Stanford parser file from the link given in readme and keep it in the same folder as your project

**Comment by Naren020402** [comment]
i did

**Comment by shoebham** [comment]
> i am not familiar with docker can you provide the link for downloading docker and how to do run it
> 
> 

you have the whole internet to get familiar with it. watch some videos or read some articles.
