### ISSUE TITLE
Stanford file

### ISSUE THREAD

**Issue by atharvauk15** [shoebham/text_to_isl#19]
After downloading the stanford-parser-full-2018-10-17 do i have to extract the file and paste it inside the folder containing main.py or directly paste it as a zip file?

**Comment by shoebham** [comment]
Let the code unzip it, if that doesnt work unzip it manually and paste where main.py is

**Comment by atharvauk15** [comment]
![Screenshot 2024-06-21 132024](https://github.com/shoebham/text_to_isl/assets/157051859/dd516a3c-41e2-4ab0-9a7e-b95e48e31362)
![Screenshot 2024-06-21 132129](https://github.com/shoebham/text_to_isl/assets/157051859/8f0d4edf-8123-4532-aba2-940ea2e0a37f)

**Comment by atharvauk15** [comment]
![image](https://github.com/shoebham/text_to_isl/assets/157051859/ec04e031-8536-4f89-94b6-60071e2347dd)
After extracting
Same issue

**Comment by shoebham** [comment]
Paste screenshot of your file directory

**Comment by atharvauk15** [comment]
![image](https://github.com/shoebham/text_to_isl/assets/157051859/3a8021b2-c2f8-41bb-ad1a-50e62166e9ae)

**Comment by shoebham** [comment]
idk bro, file should be present check if jar is present inside the unzipped folder

**Comment by atharvauk15** [comment]
![image](https://github.com/shoebham/text_to_isl/assets/157051859/16530d89-512c-4ab4-b62a-600202ae2cd1)
Searched inside the unzipped folder

**Comment by shoebham** [comment]
brother do so some debugging, google some errors you'll solve it.

**Comment by shoebham** [comment]
and you have to restart the application after unzipping

**Comment by atharvauk15** [comment]
![image](https://github.com/shoebham/text_to_isl/assets/157051859/ddbae873-b839-4d6b-9275-8272d823821e)
Error when i run script.js

**Comment by shoebham** [comment]
brother this app doesnt need node why are you running it as a node app

**Comment by atharvauk15** [comment]
Where should i run it then?
Ik its a silly doubt but plz help me

**Comment by shoebham** [comment]
why do you need to run it, the python app calls everything you don't need to run it separately.

**Comment by atharvauk15** [comment]
![image](https://github.com/shoebham/text_to_isl/assets/157051859/e0e6435d-df85-4eb7-b467-479dc7388e6a)
Error when i am running main.py. I even tried downloading the latest version of stanford parser file and using it
Created environment variable CLASSPATH in the folder where main.py is present. Also used chatgpt and followed its steps to solve the issue. Still its not running

**Comment by shoebham** [comment]
your jar path is invalid, 
<img width="146" alt="image" src="https://github.com/shoebham/text_to_isl/assets/25881429/d1570d9c-aae4-4a7f-b7bc-c3b2dd64f9cc">
fix this first, see the classpath variable
