### ISSUE TITLE
OSError: Java command failed : ['/usr/local/openjdk-8/bin/java'

### ISSUE THREAD

**Issue by jonathan2667** [shoebham/text_to_isl#20]
Title: OSError: Java command failed when using Stanford Parser

Body:

Hello,

I encountered an issue while trying to use the Stanford Parser with your project. The error indicates a failure in executing the Java command. Below are the details and steps I have taken so far:

### Environment Setup

1. **System Information**:
    - MacBook Pro with macOS.
    - Using Docker to containerize the application.

2. **Dockerfile Configuration**:
    - Python 3.9 base image.
    - OpenJDK 8 installed.
    - CLASSPATH set to `/root/stanford-parser-full-2018-10-17/*`.

3. **Environment Variables**:
    - `CLASSPATH: /root/stanford-parser-full-2018-10-17/*`
    - `JAVA_HOME: /usr/local/openjdk-8`

4. **Main Steps Taken**:
    - Built Docker image and started the container.
    - Ensured `stanford-parser-full-2018-10-17` directory is present with required JAR files.
    - Verified the Java installation and version inside the Docker container.

### Error Details

When attempting to run the Flask application and process a text input, I encountered the following error:

parser-full-2018-10-17/stanford-parser-3.9.2-models.jar:/root/stanford-parser-full-2018-10-17/stanford-parser-3.9.2-sources.jar:/root/stanford-parser-full-2018-10-17/slf4j-api-1.7.12-sources.jar:/root/stanford-parser-full-2018-10-17/stanford-parser-3.9.2-javadoc.jar:/root/stanford-parser-full-2018-10-17/stanford-parser.jar:/root/stanford-parser-full-2018-10-17/ejml-0.23.jar:/root/stanford-parser-full-2018-10-17/slf4j-api.jar:/root/stanford-parser-full-2018-10-17/stanford-parser-3.9.2-models.jar', 'edu.stanford.nlp.parser.lexparser.LexicalizedParser', '-model', 'edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz', '-sentences', 'newline', '-outputFormat', 'penn', '-tokenized', '-escaper', 'edu.stanford.nlp.process.PTBEscapingProcessor', '-encoding', 'utf8', '/tmp/tmpwl9dr1bk']

### Steps Tried

- Verified the Java version and CLASSPATH inside the container.
- Attempted to manually execute the Java command inside the container with the same classpath settings.
- Checked the contents of `stanford-parser.jar` and other related JAR files to ensure `edu.stanford.nlp.parser.lexparser.LexicalizedParser` is present.

### Output of Manual Command

```sh
root@eef94f077e3b:~# echo "how are you" > /root/test_input.txt
root@eef94f077e3b:~# java -mx4g -cp "/root/stanford-parser-full-2018-10-17/*" edu.stanford.nlp.parser.lexparser.LexicalizedParser -model edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz -sentences newline -outputFormat penn -tokenized -escaper edu.stanford.nlp.process.PTBEscapingProcessor -encoding utf8 /root/test_input.txt
Error: Could not find or load main class edu.stanford.nlp.parser.lexparser.LexicalizedPars
`````
![Screenshot 2024-07-09 at 16 14 46](https://github.com/shoebham/text_to_isl/assets/77002214/28be53dc-396a-4b6e-8168-466813a195b5)
er
![Screenshot 2024-07-09 at 16 15 04](https://github.com/shoebham/text_to_isl/assets/77002214/a4645bf4-fa1a-4363-b1a8-2e22812fbcac)

**Comment by shoebham** [comment]
Thank you for the detailed issue, Will try to reproduce this issue in my system and let you know

**Comment by jonathan2667** [comment]
![Screenshot 2024-07-10 at 14 46 38](https://github.com/shoebham/text_to_isl/assets/77002214/888ac497-b12b-4ba3-82c9-e4f7561888ca)

I get the same errors when I try locally to run via: python main.py.

I have literally tried everything at this point with ChatGpt and Google. If it would be easier for you, we can have an online meet. Please help me fix this, it would be really appreciated. 

# Issue: `Error: Could not find or load main class edu.stanford.nlp.parser.lexparser.LexicalizedParser`

## Description

I am trying to run a Flask application that uses the StanfordParser from NLTK. The application attempts to parse sentences using the StanfordParser, but it encounters an error:

Error: Could not find or load main class edu.stanford.nlp.parser.lexparser.LexicalizedParser

Many thanks!

**Comment by shoebham** [comment]
I believe you are setting invalid classpath, it should be `/root/stanford-parser-full-2018-10-17` instead of `/root/stanford-parser-full-2018-10-17/*` since * searches for the main class only in the root folder, it does not recursively goes in subdirectories for main class. See [this](https://stackoverflow.com/a/1237107/10763245).

Dont manually set classpath, it is being set on line 32
```
os.environ['CLASSPATH'] = os.path.join(BASE_DIR, 'stanford-parser-full-2018-10-17')
os.environ['STANFORD_MODELS'] = os.path.join(BASE_DIR,
                                             'stanford-parser-full-2018-10-17/edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz')
os.environ['NLTK_DATA'] = '/usr/local/share/nltk_data/'
```

**Comment by jonathan2667** [comment]
https://pastebin.com/LrVDFAhR

this is my current source code when I try to run it locally using python. The only thing that I have changed is JAVA_HOME os environ. I have tried even without adding it many times.

```
(.venv) mogovanjonathan@Mogovans-MBP text_to_isl % python main.py

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.2.2.json: 140kB [00:00, 57.4MB/s]                                                                                                                                 
2024-07-10 15:45:28 INFO: Downloading default packages for language: en (English)...
2024-07-10 15:45:28 INFO: File exists: stanza_resources/en/default.zip.
2024-07-10 15:45:31 INFO: Finished downloading models and saved to stanza_resources.
CLASSPATH: /Users/mogovanjonathan/PycharmProjects/text_to_isl2/text_to_isl/stanford-parser-full-2018-10-17
STANFORD_MODELS: /Users/mogovanjonathan/PycharmProjects/text_to_isl2/text_to_isl/stanford-parser-full-2018-10-17/edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz
JAVA_HOME: /usr/local/opt/openjdk@8
2024-07-10 15:45:31 INFO: Loading these models for language: en (English):
=========================
| Processor | Package   |
-------------------------
| tokenize  | spacy     |
| pos       | combined  |
| lemma     | combined  |
| depparse  | combined  |
| sentiment | sstplus   |
| ner       | ontonotes |
=========================

2024-07-10 15:45:31 INFO: Use device: cpu
2024-07-10 15:45:31 INFO: Loading: tokenize
/Users/mogovanjonathan/PycharmProjects/text_to_isl2/.venv/lib/python3.9/site-packages/torch/__init__.py:696: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/tensor/python_tensor.cpp:453.)
  _C._set_default_tensor_type(t)
2024-07-10 15:45:32 INFO: Loading: pos
2024-07-10 15:45:34 INFO: Loading: lemma
2024-07-10 15:45:34 INFO: Loading: depparse
2024-07-10 15:45:34 INFO: Loading: sentiment
2024-07-10 15:45:34 INFO: Loading: ner
2024-07-10 15:45:35 INFO: Done loading processors!
 * Serving Flask app 'main' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://192.168.3.202:8080/ (Press CTRL+C to quit)
192.168.3.202 - - [10/Jul/2024 15:45:42] "GET / HTTP/1.1" 200 -
192.168.3.202 - - [10/Jul/2024 15:45:42] "GET /style.css HTTP/1.1" 304 -
192.168.3.202 - - [10/Jul/2024 15:45:42] "GET /css/cwasa.css HTTP/1.1" 304 -
192.168.3.202 - - [10/Jul/2024 15:45:42] "GET /js/script.js HTTP/1.1" 304 -
192.168.3.202 - - [10/Jul/2024 15:45:42] "GET /js/allcsa.js HTTP/1.1" 304 -
here
192.168.3.202 - - [10/Jul/2024 15:45:42] "GET /static/js/sigmlFiles.json HTTP/1.1" 200 -
192.168.3.202 - - [10/Jul/2024 15:45:42] "GET /jas/loc2021/cwa/cwacfg.json HTTP/1.1" 200 -
192.168.3.202 - - [10/Jul/2024 15:45:42] "HEAD /jas/loc2021/avatars/COMMON.jar HTTP/1.1" 200 -
192.168.3.202 - - [10/Jul/2024 15:45:42] "GET /jas/loc2021/cwa/h2s.xsl HTTP/1.1" 304 -
192.168.3.202 - - [10/Jul/2024 15:45:42] "HEAD /jas/loc2021/avatars/marc.jar HTTP/1.1" 200 -
192.168.3.202 - - [10/Jul/2024 15:45:42] "GET /jas/loc2021/avatars/COMMON.jar HTTP/1.1" 200 -
192.168.3.202 - - [10/Jul/2024 15:45:42] "GET /jas/loc2021/avatars/marc.jar HTTP/1.1" 304 -
192.168.3.202 - - [10/Jul/2024 15:45:43] "GET /jas/loc2021/cwa/shaders/qskin.frag HTTP/1.1" 304 -
192.168.3.202 - - [10/Jul/2024 15:45:43] "GET /jas/loc2021/cwa/shaders/qskin.vert HTTP/1.1" 304 -
text is about
/Users/mogovanjonathan/PycharmProjects/text_to_isl2/text_to_isl/main.py:259: DeprecationWarning: The StanfordParser will be deprecated
Please use nltk.parse.corenlp.CoreNLPParser instead.
  parser = StanfordParser()
Error: Could not find or load main class edu.stanford.nlp.parser.lexparser.LexicalizedParser

[2024-07-10 15:45:48,417] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/Users/mogovanjonathan/PycharmProjects/text_to_isl2/.venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mogovanjonathan/PycharmProjects/text_to_isl2/.venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mogovanjonathan/PycharmProjects/text_to_isl2/.venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mogovanjonathan/PycharmProjects/text_to_isl2/.venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/mogovanjonathan/PycharmProjects/text_to_isl2/text_to_isl/main.py", line 380, in flask_test
    take_input(text)
  File "/Users/mogovanjonathan/PycharmProjects/text_to_isl2/text_to_isl/main.py", line 326, in take_input
    convert(some_text);
  File "/Users/mogovanjonathan/PycharmProjects/text_to_isl2/text_to_isl/main.py", line 335, in convert
    word_list[i]=reorder_eng_to_isl(words)
  File "/Users/mogovanjonathan/PycharmProjects/text_to_isl2/text_to_isl/main.py", line 261, in reorder_eng_to_isl
    possible_parse_tree_list = [tree for tree in parser.parse(input_string)]
  File "/Users/mogovanjonathan/PycharmProjects/text_to_isl2/.venv/lib/python3.9/site-packages/nltk/parse/api.py", line 47, in parse
    return next(self.parse_sents([sent], *args, **kwargs))
  File "/Users/mogovanjonathan/PycharmProjects/text_to_isl2/.venv/lib/python3.9/site-packages/nltk/parse/stanford.py", line 138, in parse_sents
    self._execute(
  File "/Users/mogovanjonathan/PycharmProjects/text_to_isl2/.venv/lib/python3.9/site-packages/nltk/parse/stanford.py", line 260, in _execute
    stdout, stderr = java(
  File "/Users/mogovanjonathan/PycharmProjects/text_to_isl2/.venv/lib/python3.9/site-packages/nltk/internals.py", line 140, in java
    raise OSError("Java command failed : " + str(cmd))
OSError: Java command failed : ['/usr/local/opt/openjdk@8/bin/java', '-mx4g', '-cp', '/Users/mogovanjonathan/PycharmProjects/text_to_isl2/text_to_isl/stanford-parser-full-2018-10-17/stanford-parser-3.9.2-models.jar:/Users/mogovanjonathan/PycharmProjects/text_to_isl2/text_to_isl/stanford-parser-full-2018-10-17/ejml-0.23.jar:/Users/mogovanjonathan/PycharmProjects/text_to_isl2/text_to_isl/stanford-parser-full-2018-10-17/slf4j-api.jar:/Users/mogovanjonathan/PycharmProjects/text_to_isl2/text_to_isl/stanford-parser-full-2018-10-17/stanford-parser-3.9.2-models.jar:/Users/mogovanjonathan/PycharmProjects/text_to_isl2/text_to_isl/stanford-parser-full-2018-10-17/stanford-parser-3.9.2-sources.jar:/Users/mogovanjonathan/PycharmProjects/text_to_isl2/text_to_isl/stanford-parser-full-2018-10-17/stanford-parser-3.9.2-javadoc.jar:/Users/mogovanjonathan/PycharmProjects/text_to_isl2/text_to_isl/stanford-parser-full-2018-10-17/stanford-parser.jar:/Users/mogovanjonathan/PycharmProjects/text_to_isl2/text_to_isl/stanford-parser-full-2018-10-17/slf4j-api-1.7.12-sources.jar', 'edu.stanford.nlp.parser.lexparser.LexicalizedParser', '-model', 'edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz', '-sentences', 'newline', '-outputFormat', 'penn', '-tokenized', '-escaper', 'edu.stanford.nlp.process.PTBEscapingProcessor', '-encoding', 'utf8', '/var/folders/l8/kz7v1q312pb4hdcg4vczlyfr0000gn/T/tmp6vmst4x0']
192.168.3.202 - - [10/Jul/2024 15:45:48] "POST / HTTP/1.1" 500 -

```
I do not understand why... do you have 10 minutes to look on a google meet? Sorry for bothering you!

**Comment by shoebham** [comment]
sure, shoot me the google meet link at me@shubhwym.me

**Comment by shoebham** [comment]
dont run this inside venv, it causes problems. either run it without virtual environment or use docker

**Comment by jonathan2667** [comment]
ok, I will try first to run it without vent and if I do not manage and get the same error, I would really appreciate whenever you have time later if it is not late for you, or tomorrow at any time you want, a google meet to help me fix it. thank you so much for your help. ill come back after trying without vent.

**Comment by shoebham** [comment]
also try to use docker
i simplified requirements and update the dockerfile, if you dont want docker, try to set the same java home as dockerfile
Dockerfile:
ENV JAVA_HOME /usr/local/openjdk-8

**Comment by jonathan2667** [comment]
Ok, thank you! I ll be back after I manage to run it locally without vent. Many thanks! :)

**Comment by jonathan2667** [comment]
Sir, I solved it. The problem is that if you do not have git ifs installed, it will install only some files of the parser. It would be a great idea to tell the others that they should install git ifs first or another idea is to let the people install the zip from your google drive link and just take the folder out of the repo the one that is already there in the files when you clone them.

**Comment by shoebham** [comment]
Oh nice catch! 
Will remove it. Thanks for your help! Anything else you need help with? if not can you close this issue.

Thanks!

**Comment by jonathan2667** [comment]
Thank you with your help solving this and your fast answers. Amazing work!
