### ISSUE TITLE
i cant run the project if you can help me in this 

### ISSUE THREAD

**Issue by 00SoCRaT00** [shoebham/text_to_isl#7]

**Comment by 00SoCRaT00** [comment]
![image](https://user-images.githubusercontent.com/83826259/209452068-241a48e7-534d-42aa-bd8e-c0114fb7f7c1.png)

**Comment by shoebham** [comment]
Hi @00SoCRaT00 , so sorry for the late reply just saw this, can you please provide the full error by copying it from the console?

**Comment by shoebham** [comment]
I think its probably some installation issue, please try installing spacy again by ```pip install spacy```

**Comment by 00SoCRaT00** [comment]
i go to another project and also give me error and i cant run it 
if you can help me in it 
![image](https://user-images.githubusercontent.com/83826259/210153580-77fac970-f196-46cc-8811-22600b42c3cd.png)
![image](https://user-images.githubusercontent.com/83826259/210153582-746405e0-01f7-4a16-a2b6-49c3b90e63ca.png)
this is an error of the console

**Comment by 00SoCRaT00** [comment]
here is some error of your project 
i tried to solve some of it but i cant run it 
![image](https://user-images.githubusercontent.com/83826259/210154431-ee76da30-4860-4d9a-a8c3-6b48493a08ba.png)
this is pic of terminal
i hope you can hello me 
and i think alse there is an error in python file main

**Comment by shoebham** [comment]
what steps did you follow to run the commands, can you please list them.

The command i use to run this project is ```python main.py```  it deploys the project, downloads stanford parser first then runs,
The steps i would suggest following are:
```
git clone https://github.com/shoebham/text_to_isl
python main.py
open http://127.0.0.1:5000/ or whatever url console gives
enter any text inside the input box
you will notice first it will download stanford parser in that directory and give some weird erro
now enter text again in input box it should work.
