### ISSUE TITLE
hello can u help me please 

### ISSUE THREAD

**Issue by 00SoCRaT00** [shoebham/text_to_isl#8]
after much error i finally run the project but only one error still 
when i type any thing in the input box it gives me error like that 
![image](https://user-images.githubusercontent.com/83826259/210155746-5148c1a9-58ea-4839-9bcd-c92695818ca1.png)
and give me this in terminal
![image](https://user-images.githubusercontent.com/83826259/210155752-919da081-b5c6-425f-9354-77ef2ed28fbf.png)
 i hope you help me as fast as you can 
 thank you

**Comment by shoebham** [comment]
you need to install Java and set JAVAHOME environment variable,
